name: ClusterFuzzLite continuous build

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!**/*.md"
      - "!docs/**"
  workflow_dispatch:

permissions: {}

concurrency:
  group: clusterfuzzlite-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    name: Save main fuzz build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read # Compare and retain ClusterFuzzLite build artifacts.
      contents: read
    steps:
      - name: Build and upload fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          language: rust
          sanitizer: address
          upload-build: true
